apiVersion: v1
kind: Secret
metadata:
    name: postgres-access
type: Opaque
data:
    password: ENC[AES256_GCM,data:lYmWqWtbA6s=,iv:vi/dK9MW19/jJnUp9zop1Z+8oYvLjISlJgrzrzgqb+Q=,tag:RjiGuGD5dumba8eezFw9FA==,type:str]
    username: ENC[AES256_GCM,data:CvPeUCzrqgU=,iv:VAUJqnkMUbccrtun04eq/VlZdpY/OGV06es11HVQd+U=,tag:V1q2ebO/OZnzyKnCh4X1fA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-06-14T12:52:10Z"
    mac: ENC[AES256_GCM,data:WhqJIQ7oJkZwWpTyG25ILUxuRNi9iAPngvH+JudroCYkbHfgXI7JnKCL4tXhMThY5K2dDpnMpTWYHC65TwVPpw6mNc5pO1JNVfeer8VGwI2DlBoB86zgs7a6uyNPdtnmzKB9IZcW4ChKkv7Y7kGsRdicJo2we88npBAY6/fegpM=,iv:PF2ePB6JsLINdSdyBu+P0lOhknLNK4yk0QW33Z1QDRM=,tag:HP17Bp3aHx+DBF46Pe+M7g==,type:str]
    pgp:
        - created_at: "2024-06-14T12:51:40Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dz+YshEceNvUSAQdAmM9xGZV45dxZCd0tXtDNoBQzIpsHnwkzmcSz40xn6yIw
            64My8CQPTxJTzkfohWMIOX76Q7qaUJHVPLaI4U62KWktpAw3e3zSCknifI6Kh9th
            1GgBCQIQMOCuUhmzEcRUdw4U/Ak/raYNS9pptS+LeYedhUg9ynRpU4AU5G13GDR6
            nmPD58YxDO7X7XMi3UN1C+4EXmdQyHvMUHluEZp/zRdG4amzWfT1CW41pXs8gZWX
            xy2JM6dBxrQfVw==
            =+I3z
            -----END PGP MESSAGE-----
          fp: 7506E7A1179D5FEA903B4639AC61D33EFF3637A9
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.8.1
