apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv-volume
  labels:
    type: local
    app.kubernetes.io/part-of: jpat
  annotations:
    pv.beta.kubernetes.io/gid: "1234"
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
