apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./argocd
  - ./postgresql
  - ./back-end

generatorOptions:
  labels:
    app.kubernetes.io/part-of: jpat

buildMetadata:
  - managedByLabel
  - originAnnotations
