apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - argocd-cm.yaml
  - argocd-repo-server.yaml
  - project.yaml
  - application.yaml

patches:
  - path: argocd-repo-server-ksops-patch.yaml

generators:
  - ./secret-generator.yaml
