apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: default-secret-generator
  kind: ksops
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./sops-age-secret.enc.yaml
