apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: jpat-dev-

resources:
  - ../../base

patches:
  - path: service.yaml
    target:
      kind: Service
      version: v1
      name: nodeport
  - path: deployment.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
  - path: ingress.yaml
    target:
      group: networking.k8s.io
      kind: Ingress
      version: v1

transformers:
  - label-app-version.yaml
