apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgres

resources:
  - namespace.yaml
  - service.yaml
  - pv.yaml
  - pv-claim.yaml
  - statefulset.yaml

configMapGenerator:
  - name: postgres-connection
    envs:
      - ./config/postgres.envs
    options:
      disableNameSuffixHash: true

generators:
  - ./secret-generator.yaml
