apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - argocd-cm.yaml
  - argocd-repo-server.yaml

patches:
  - path: argocd-repo-server-ksops-patch.yaml
