apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kans-elixir-dev

resources:
  - ./namespace.yaml
  - ../../../../kp15s/overlays/dev

patches:
  - path: ingress.yaml
    target:
      group: networking.k8s.io
      kind: Ingress
      version: v1

images:
  - name: kaap
    newName: elixir-dev
    newTag: 0.4.0

components:
  - ../../../../kp15s/components/postgres
