apiVersion: v1
kind: Service
metadata:
  name: nodeport
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/name: kans
    app.kubernetes.io/part-of: jpat
  annotations:
    prometheus.io/scrape: "true"
spec:
  selector:
    app.kubernetes.io/name: kans
  type: NodePort
  ports:
    - name: tcp-probe
      port: 4009
      protocol: TCP
      targetPort: 3001
    - name: tcp-api
      port: 4002
      protocol: TCP
      targetPort: 4000
    - name: http
      port: 8080
      targetPort: http-metrics
