apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ../../base

patches:
  - path: deployment.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
transformers:
  - label-app-version.yaml
namePrefix: jpat-dev-
namespace: kans-elixir-dev
# images:
#   - name: elixir-dev
#     newTag: 0.1.0
