apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ../../base

patches:
  - path: deployment.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
  - path: ingress.yaml
    target:
      group: networking.k8s.io
      kind: Ingress
      version: v1
transformers:
  - label-app-version.yaml
namePrefix: jpat-dev-
namespace: kans-elixir-dev
images:
  - name: kaap
    newName: elixir-dev
    newTag: 0.2.0
